# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 787)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(84,111,236);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:18px;\n"
"background-color: rgb(84,111,236);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setContentsMargins(10, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(self.frame_superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(250, 36))
        self.btn_menu.setMaximumSize(QtCore.QSize(250, 36))
        self.btn_menu.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-radius: 5px\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(36, 36))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_2.addWidget(self.btn_menu)
        spacerItem = QtWidgets.QSpacerItem(844, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_min = QtWidgets.QPushButton(self.frame_superior)
        self.btn_min.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_min.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon1)
        self.btn_min.setIconSize(QtCore.QSize(36, 36))
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_max = QtWidgets.QPushButton(self.frame_superior)
        self.btn_max.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_max.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_max.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/chevrons-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_max.setIcon(icon2)
        self.btn_max.setIconSize(QtCore.QSize(36, 36))
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_normal = QtWidgets.QPushButton(self.frame_superior)
        self.btn_normal.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_normal.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_normal.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normal.setIcon(icon3)
        self.btn_normal.setIconSize(QtCore.QSize(36, 36))
        self.btn_normal.setObjectName("btn_normal")
        self.horizontalLayout_2.addWidget(self.btn_normal)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setStyleSheet("QPushButton:hover{\n"
"background-color: rgb(230,0,0);\n"
"}")
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(36, 36))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 10px;")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menu = QtWidgets.QFrame(self.frame_contenido)
        self.frame_menu.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"background-color: rgb(230, 240, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(84,111,236);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"font: 77 14pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(39,74,233);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 77 14pt \"Arial Black\";\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:rgb(84,111,236);\n"
"font: 77 16pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout_4.setContentsMargins(-1, 16, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_deteccion = QtWidgets.QPushButton(self.frame_menu)
        self.btn_deteccion.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_deteccion.setMaximumSize(QtCore.QSize(190, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_deteccion.setIcon(icon5)
        self.btn_deteccion.setIconSize(QtCore.QSize(30, 30))
        self.btn_deteccion.setObjectName("btn_deteccion")
        self.verticalLayout_2.addWidget(self.btn_deteccion)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.btn_basedatos = QtWidgets.QPushButton(self.frame_menu)
        self.btn_basedatos.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_basedatos.setMaximumSize(QtCore.QSize(190, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_basedatos.setIcon(icon6)
        self.btn_basedatos.setIconSize(QtCore.QSize(30, 30))
        self.btn_basedatos.setObjectName("btn_basedatos")
        self.verticalLayout_2.addWidget(self.btn_basedatos)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btn_ajustes = QtWidgets.QPushButton(self.frame_menu)
        self.btn_ajustes.setMinimumSize(QtCore.QSize(190, 50))
        self.btn_ajustes.setMaximumSize(QtCore.QSize(190, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ajustes.setIcon(icon7)
        self.btn_ajustes.setIconSize(QtCore.QSize(30, 30))
        self.btn_ajustes.setObjectName("btn_ajustes")
        self.verticalLayout_2.addWidget(self.btn_ajustes)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.frame_menu)
        self.label.setMinimumSize(QtCore.QSize(150, 150))
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/escudo_negativo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addWidget(self.frame_menu)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_deteccion = QtWidgets.QWidget()
        self.page_deteccion.setObjectName("page_deteccion")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_deteccion)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(177, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_video = QtWidgets.QLabel(self.page_deteccion)
        self.label_video.setMinimumSize(QtCore.QSize(640, 480))
        self.label_video.setMaximumSize(QtCore.QSize(640, 480))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.verticalLayout_6.addWidget(self.label_video)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page_deteccion)
        self.label_3.setMinimumSize(QtCore.QSize(220, 30))
        self.label_3.setMaximumSize(QtCore.QSize(220, 30))
        self.label_3.setStyleSheet("color:rgb(84,111,236);\n"
"font: 77 14pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_text_placa = QtWidgets.QLabel(self.page_deteccion)
        self.label_text_placa.setMinimumSize(QtCore.QSize(190, 30))
        self.label_text_placa.setMaximumSize(QtCore.QSize(190, 30))
        self.label_text_placa.setStyleSheet("color:rgb(0,0,0);\n"
"font: 14pt \"Franklin Gothic Demi Cond\";\n"
"\n"
"\n"
"")
        self.label_text_placa.setObjectName("label_text_placa")
        self.horizontalLayout_6.addWidget(self.label_text_placa)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        spacerItem12 = QtWidgets.QSpacerItem(176, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.stackedWidget.addWidget(self.page_deteccion)
        self.page_base_datos = QtWidgets.QWidget()
        self.page_base_datos.setObjectName("page_base_datos")
        self.stackedWidget.addWidget(self.page_base_datos)
        self.page_ajustes = QtWidgets.QWidget()
        self.page_ajustes.setObjectName("page_ajustes")
        self.stackedWidget.addWidget(self.page_ajustes)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout.addWidget(self.frame_contenido)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_deteccion.setText(_translate("MainWindow", " Detección"))
        self.btn_basedatos.setText(_translate("MainWindow", " Base Datos"))
        self.btn_ajustes.setText(_translate("MainWindow", " Ajustes"))
        self.label_3.setText(_translate("MainWindow", "Placa Detectada:"))
        self.label_text_placa.setText(_translate("MainWindow", "ABC123"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
